# Spring properties
# Service registry under this name
spring:
  application:
    name: spring-cloud-eureka-feign-client

# Discovery server access
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:2222/eureka/}

# HTTP (Tomcact) port
server:
  port: 2224